### ISSUE TITLE
Unused parameter warnings

### ISSUE THREAD

**Issue by tehsphinx** [mikepb/go-serial#3]
As soon as I use this package somewhere in my code I always get these warnings. If not problematic so it is at least very annoying.

Already the `go get` command shows:

`Apples-MacBook-Pro:src $ go get github.com/mikepb/go-serial/`
`# github.com/mikepb/go-serial`
`.../github.com/mikepb/go-serial/_obj/_cgo_main.c:2:61: warning: unused parameter 'a' [-Wunused-parameter]`
`.../github.com/mikepb/go-serial/_obj/_cgo_main.c:2:23: warning: unused parameter 'fn' [-Wunused-parameter]`
`.../github.com/mikepb/go-serial/_obj/_cgo_main.c:2:68: warning: unused parameter 'c' [-Wunused-parameter]`
`.../github.com/mikepb/go-serial/_obj/_cgo_main.c:2:85: warning: unused parameter 'ctxt' [-Wunused-parameter]`
`.../github.com/mikepb/go-serial/_obj/_cgo_main.c:4:41: warning: unused parameter 'ctxt' [-Wunused-parameter]`
`.../github.com/mikepb/go-serial/_obj/_cgo_main.c:6:26: warning: unused parameter 'a' [-Wunused-parameter]`
`.../github.com/mikepb/go-serial/_obj/_cgo_main.c:6:33: warning: unused parameter 'c' [-Wunused-parameter]`
`.../github.com/mikepb/go-serial/_obj/_cgo_main.c:7:23: warning: unused parameter 'a' [-Wunused-parameter]`
`.../github.com/mikepb/go-serial/_obj/_cgo_main.c:7:30: warning: unused parameter 'c' [-Wunused-parameter]`

Am I doing something wrong?

I tested it with go 1.6 and go 1.7.1: same issue.

**Comment by mikepb** [comment]
Sorry, I haven’t programmed in Go for a while. Please feel free to fork and update the library.

**Comment by tehsphinx** [comment]
I will close this. Have moved on to another serial package since.
